version: "3.8"

services:
  quickfin:
    image: jamievangeysel/quickfin-website:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.worker == true]
      resources:
        reservations:
          memory: 4M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.quickfin-wan.rule=Host(`quickfin.be`, `www.quickfin.be`)"
        - "traefik.http.routers.quickfin-wan.entrypoints=web"
        - "traefik.http.services.quickfin-wan.loadbalancer.server.port=80"
    healthcheck:
      test: wget -q --spider http://localhost/ || exit 1
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 2
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
